version: "3.9"

services:
  # -------- Spark master --------
  spark-master:
    image: bitnami/spark:3.5.0
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "8080:8080" # UI
      - "7077:7077" # RPC
    networks: [spark-net]

  # -------- Spark workers --------
  spark-worker-1:
    image: bitnami/spark:3.5.0
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on: [spark-master]
    ports: ["8081:8081"]
    volumes:
      - ../app/spark-job/src/main/resources:/opt/data:ro
    networks: [spark-net]

  spark-worker-2:
    image: bitnami/spark:3.5.0
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on: [spark-master]
    ports: ["8082:8081"]
    volumes:
      - ../app/spark-job/src/main/resources:/opt/data:ro
    networks: [spark-net]

  spark-worker-3:
    image: bitnami/spark:3.5.0
    container_name: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on: [spark-master]
    ports: ["8083:8081"]
    volumes:
      - ../app/spark-job/src/main/resources:/opt/data:ro
    networks: [spark-net]

  # -------- Spark client --------
  spark-client:
    image: bitnami/spark:3.5.0
    container_name: spark-client
    command: ["tail", "-f", "/dev/null"]
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ../app/spark-job/target:/opt/app
      - ../app/spark-job/src/main/resources:/opt/data:ro
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
      - spark-worker-3
      - postgres
    tty: true
    stdin_open: true
    networks: [spark-net]

  # -------- PostgreSQL --------
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=spark
      - POSTGRES_PASSWORD=spark123
      - POSTGRES_DB=sparkdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks: [spark-net]
    # -------- pgAdmin (interface web PostgreSQL) --------
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80" # Accès via navigateur à http://localhost:5050
    depends_on:
      - postgres
    networks: [spark-net]

networks:
  spark-net:
    driver: bridge

volumes:
  pgdata:
